# Generated by Django 3.2.4 on 2022-01-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_social_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
    ]
