# Generated by Django 3.2.4 on 2022-02-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
