# Generated by Django 3.2.4 on 2022-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(choices=[('junior', '0-2 years'), ('medium', '2-4 years'), ('senior', '4+ years')], default='0-2 years', max_length=200),
        ),
    ]
