# Generated by Django 3.2.4 on 2022-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(choices=[('0-2 years', '0-2 years'), ('2-4 years', '2-4 years'), ('4+ years', '4+ years')], default='0-2 years', max_length=200),
        ),
    ]
