# Generated by Django 3.2.4 on 2022-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='store-images/default.jpg', null=True, upload_to='store-images/'),
        ),
    ]
