# Generated by Django 3.2.4 on 2022-04-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
