# Generated by Django 3.2.4 on 2022-05-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20220506_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qtyInStock',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
