# Generated by Django 3.2.4 on 2022-01-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_review_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-total_votes', 'title']},
        ),
    ]
