# Generated by Django 3.2.4 on 2022-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220207_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project-images/default.jpg', null=True, upload_to='project-images/'),
        ),
    ]
