# Generated by Django 3.2.4 on 2022-02-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='static/images/project-images/default.jpg', null=True, upload_to='static/images/project-images/'),
        ),
    ]
