# Generated by Django 3.2.4 on 2022-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('development', 'Software Development'), ('datasci', 'Data Science'), ('network', 'Network Management'), ('sysadm', 'System Administration'), ('other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
