# Generated by Django 3.2.4 on 2022-04-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Software Development', 'development'), ('Data Science', 'datasci'), ('Network Management', 'network'), ('System Administration', 'sysadm'), ('Other', 'other')], max_length=200),
        ),
    ]
